### ISSUE TITLE
Namespace error

### ISSUE THREAD

**Issue by rohitmel** [gettyimages/gettyimages-api_php#16]
src/ApiClient.php should be src/GettyImages_Client.php

i had to manually include the file to get it working otherwise

require_once 'vendor/gettyimages/gettyimages-api/src/ApiClient.php';

**Comment by CaseyMacPherson** [comment]
Looking into this now.

**Comment by jeffgoo** [comment]
Hi Rohitmel.  I pushed a fix.  The FeatureContext.php was referencing a php file in the phar when it should have just been referencing the phar and letting the phar manage what files it is composed of.   This has been fixed and pushed into master.  Sorry about this.  -Jeff

**Comment by rohitmel** [comment]
Thanks guys. All works as expected. Thx
