### ISSUE TITLE
Setting "accept-language" header

### ISSUE THREAD

**Issue by mamedia-edv** [gettyimages/gettyimages-api_php#2]
Hey guys,

as far as I can see there is no other possibility to set the "accept-language" header other than by changing the source code of your php SDK. Or am I missing here something? It would be really handy if I could set additional curl options e. g. via a method in der FluentRequest class which will pass the options to the WebHelper object once it has been created. Is something like that planned in the near future or am I on my own on this?

Thanks,
Andreas

**Comment by mapitman** [comment]
The PHP version of the SDK does not currently support it. If you'd like to add it and submit a pull request, we'd be happy to accept it. Our .NET SDK does support it and you can see how it is implemented [here](https://github.com/gettyimages/gettyimages-api_dotnet/blob/master/GettyImages.Api/Search/SearchImages.cs#L35). If you do decide to submit a pull request, please be sure to add a test for it as well.
