### ISSUE TITLE
Curl SSH verify environment variable

### ISSUE THREAD

**Issue by bSushil** [gettyimages/gettyimages-api_php#22]
Hi
I would prefer if we could set GettyImagesApi_IgnoreSSLValidation within the code rather than an environment variable. This would give the programmer more control and the code would be machine independent. Otherwise, we will have to set the environment in every machine we install this api, which is not a good solution.

**Comment by CaseyMacPherson** [comment]
bSushil,

First, thank you for trying out the SDK. We made the decision to use environment variables as this is the usual convention for setting server wide settings. IgnoringSSL is a pretty deliberate choice and we wanted to make that very clear. I'd be curious as to why you're needing to Ignore ssl validation against our api.

An easy workaround would be to put this in your PHP code and it will effectively have the same behavior.

putenv(''GettyImagesApi_IgnoreSSLValidation");

Reference: http://php.net/manual/en/function.putenv.php

Additionally if you wanted to expose this setting in a programmatic way where exporting the environment variable isn't preferable, I'd consider looking at FluentRequest as the place to create the extension, possibly the Execute() method. Then send a pull request.

Thanks!
-Casey

**Comment by bSushil** [comment]
I agree your decision to set environment variable. But you have to consider this as well: there will be a number of websites running in a server. Setting an environment variable will affect all other applications. So it is better to have a localized variable definition. No need to make server wide change. I believe that is the best way to do.

As for me, I had to modify your code to make it work. I modified your code in the file WebHelper.php in line 97 and 98. The thing I didn't is not a good thing to do. It would be better if we did something like this:

$client = new GettyImages_Client(Yii::$app->params['gettyImages']['appKey'], Yii::$app->params['gettyImages']['appSecret']);;
$client->setGettyImageCurlSSHVerifyHost(0);
$client->setGettyImageCurlSSHVerifyPeer(0);

This will keep the library and the server clean for any messy environment variable or code modification by programmer like I did.
