### ISSUE TITLE
Querystring parameters not supported yet?

### ISSUE THREAD

**Issue by tistre** [gettyimages/gettyimages-api_php#26]
Hi,

is it true that the “querystring parameters” as documented in the [/details/id API docs](http://developers.gettyimages.com/api/docs/v3/images/id/get/#querystring-parameters) cannot be set via the PHP client yet?

I want to fetch image details like this, only via the PHP client:

 https://api.gettyimages.com/v3/images/474390851?fields=detail_set,display_set

The following works, but I cannot pass the fields (the Fields() method doesn’t work with 'detail_set' etc.):

```
$response = $client
    ->Images()
    ->withId('474390851')
    ->execute();
```

I can create a PR for a FluentRequest::Querystring() method if you want.

Thanks,
Tim

**Comment by jsandtoast** [comment]
Hey Tim,

It seems you need withResponseField()  in your call:

```
$response = $client
    ->Images()
    ->withId('474390851') 
    ->withResponseField('detail_set')
    ->execute();
```

Let us know if that works for you.

-James

**Comment by tistre** [comment]
Hi James,

that does the job, sorry for me missing it.

Thanks a lot for the quick reply,
Tim
